create table users
(
    id              integer generated by default as identity,
    created_date    timestamp(6) with time zone default NOW() not null,
    username        varchar(255)                              not null unique,
    primary key (id)
);